### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by dri-richard** [RageAgainstThePixel/setup-ovr-platform-util#19]
It would be useful to support Linux, now that ovr-platform-util is available on that platform.
We use a Linux runner with a Unity game-ci builder, as it's easier to have it automatically install the required Android SDK 32.

**Comment by StephenHodgson** [comment]
Meta does not have a Linux binary for this.

**Comment by StephenHodgson** [comment]
> it's easier to have it automatically install the required Android SDK 32.

My [unity-setup action](https://github.com/marketplace/actions/buildalon-unity-setup) does the same thing but without the docker container which makes it easier to build il2cpp.

**Comment by StephenHodgson** [comment]
All of our buildalon unity actions are verified by GitHub. Check them out! 😁

[![marketplace](https://img.shields.io/static/v1?label=&labelColor=505050&message=Buildalon%20Actions&color=FF1E6F&logo=github-actions&logoColor=0076D6)](https://github.com/marketplace?query=buildalon)

**Comment by StephenHodgson** [comment]
![image](https://github.com/user-attachments/assets/fcd3d618-321b-4156-a1d0-d0554be90b87)

Ahh closed this too hastily. You're right @dri-richard they did add support.

**Comment by StephenHodgson** [comment]
@dri-richard you should still check out our actions. Game-CI isn't in active development afaik

**Comment by dri-richard** [comment]
Thanks, will do.
